# Generated by Django 3.0.5 on 2020-04-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off_id',
            field=models.BigIntegerField(default=1914),
            preserve_default=False,
        ),
    ]
