# Generated by Django 3.0.5 on 2020-04-29 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0009_auto_20200429_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedproduct',
            name='saved_product',
        ),
        migrations.AddField(
            model_name='savedproduct',
            name='original_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_products', to='finder.Product'),
        ),
        migrations.AddField(
            model_name='savedproduct',
            name='sub_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savedproducts', to='finder.Product'),
        ),
    ]
